export const AndrianReducerTypes = {
  ADD_CHARACTERS: "ADD_CHARACTERS",
  ADD_MORE_CHARACTERS: "ADD_MORE_CHARACTERS",
  SET_LOADING: "SET_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_USERS:"SET_USERS"

};
export const CvReducerTypes={
  SET_CV_INFO:"SET_CV_INFO",
  CV_INFO_ON_INIT:"CV_INFO_ON_INIT"
}
export const TimeReducer={
  GET_TIME:"GET_TIME",
 
}
export const ChatReducerTypes={
  GET_INFO:"GET_INFO",
  PUSH_MESSAGE:"PUSH_MESSAGE",
  DELETE_MESSAGE:"DELETE_MESSAGE",
  USER_WITH_CHAT:"USER_WITH_CHAT"
}